### ISSUE TITLE
research how to improve build time for dev and tests

### ISSUE THREAD

**Issue by kaiomagalhaes** [codelittinc/node-graphql-base-project#45]

**Comment by Gabrielpanga** [comment]
Created a PR related to this.
If we assure that we are always using the `build-watch` task, we can assure that test run without needed to rebuild the whole solution.

**Comment by kaiomagalhaes** [comment]
@Gabrielpanga we need to create a node task for it on the package.json

**Comment by Gabrielpanga** [comment]
@kaiomagalhaes Although this works like a charm, i will be reviewing `ts-node` that will avoid us to do that. 
On the other hand i can create a npm script for that, but keep in mind that the tsc -w needs to run in a separate terminal, thats what VSCode resolves for us.
